version: '1.0'
services:
  api:
    container_name: movies_express_api_app
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    command: >
      sh -c "npm run start"