openapi: 3.0.0
info:
  title: Movie API
  version: 1.0.0
components:
  schemas:
    Movie:
      type: object
      required:
        - plot
        - genres
        - cast
        - poster
        - title
        - type
      properties:
        plot:
          type: string
        genres:
          type: array
          items:
            type: string
        runtime:
          type: integer
        cast:
          type: array
          items:
            type: string
        num_mflix_comments:
          type: integer
        poster:
          type: string
        title:
          type: string
        fullplot:
          type: string
        languages:
          type: array
          items:
            type: string
        released:
          type: string
          format: date
        directors:
          type: array
          items:
            type: string
        writers:
          type: array
          items:
            type: string
        awards:
          type: object
          properties:
            wins:
              type: integer
            nominations:
              type: integer
            text:
              type: string
        lastupdated:
          type: string
          format: date-time
        year:
          type: integer
        imdb:
          type: object
          properties:
            rating:
              type: number
            votes:
              type: integer
            id:
              type: integer
        countries:
          type: array
          items:
            type: string
        type:
          type: string
        tomatoes:
          type: object
          properties:
            viewer:
              type: object
              properties:
                rating:
                  type: number
                numReviews:
                  type: integer
                meter:
                  type: integer
            lastUpdated:
              type: string
              format: date-time